---
title: "spatial 3"
output: html_notebook
---
```{r libraries, messages="FALSE"}
library(RandomFields)
library(RNGforGPD) # gen poisson
library(plgp) # distance
library(mvtnorm)
library(ggplot2)
library(viridis)
library(hrbrthemes)
```

```{r}
nu = 0.5
theta = 1
model = RMmatern(nu=1/2, var=1, scale=theta)
from <- 0
to <- 20
x.seq <- seq(from, to, length=1000) 
y.seq <- seq(from, to, length=1000)
simu <- RFsimulate(model, x=x.seq, y=x.seq)
```

```{r}
lambda = 10
eta = 0.5
coords = coordinates(simu)
values = simu$variable1
transformed = QuantileGpois(pnorm(values), lambda, eta)
s.mean = mean(transformed)
s.var = var(transformed)
df = data.frame(cbind(coords, transformed))
names(df) = c("s1", "s2", "Counts")

df.untransformed = data.frame(cbind(coords, values))
names(df.untransformed) = c("s1", "s2", "Density")
mu.hat = mean(values)
sigsq.hat = var(values)
```

```{r}
hmap.untransformed = ggplot() +
  geom_tile(data=df.untransformed, aes(x=s1, y=s2, fill=Density)) +
  labs(title = bquote("Gaussian" ~ mu==0),
       subtitle=bquote("1000x1000 Matern" ~ nu==.(nu)*", " ~ theta==1),
       caption=bquote("Sample mean="*.(round(mu.hat,2)) ~ "Sample variance="*.(round(sigsq.hat,2)))) +
  scale_fill_viridis(option="magma") +
  theme_minimal()
hmap.untransformed
```

```{r}
hmap = ggplot() +
  geom_tile(data=df, aes(x=s1, y=s2, fill=Counts)) +
  labs(title = bquote("Generalized Poisson" ~ lambda==.(lambda)* ~ eta==.(eta)),
       subtitle=bquote("1000x1000 Matern" ~ nu==.(nu)*", " ~ theta==1),
       caption=bquote("Sample mean="*.(round(s.mean,2)) ~ "Sample variance="*.(round(s.var,2)))) +
  scale_fill_viridis(option="magma", limits=c(0,65)) +
  theme_minimal()
hmap
#ggsave("1000gpoisson.png", plot=hmap, dpi=600, width=5, height=5)
```


```{r}
model = RMwave(var=1, scale=0.35)
from <- 0
to <- 20
x.seq <- seq(from, to, length=1000) 
y.seq <- seq(from, to, length=1000)
simu <- RFsimulate(model, x=x.seq, y=y.seq)
```

```{r}
lambda = 10
eta = 0.5
coords = coordinates(simu)
values = simu$variable1
transformed = QuantileGpois(pnorm(values), lambda, eta)
s.mean = mean(transformed)
s.var = var(transformed)
df = data.frame(cbind(coords, transformed))
names(df) = c("s1", "s2", "Counts")
```


```{r}
hmap = ggplot() +
  geom_tile(data=df, aes(x=s1, y=s2, fill=Counts)) +
  labs(title = bquote("Generalized Poisson" ~ lambda==.(lambda)* ~ eta==.(eta)),
       subtitle=bquote("1000x1000 Wave" ~ sigma^2==1 ~ phi == 0.25),
       caption=bquote("Sample mean="*.(round(s.mean,2)) ~ "Sample variance="*.(round(s.var,2)))) +
  scale_fill_viridis(option="magma") +
  theme_minimal()
hmap
#ggsave("1000gpoisson.png", plot=hmap, dpi=600, width=5, height=5)
```